name: æ„å»º

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean
        
      type_VM:
        description: 'Q35 or i440fx type of VM in Unraid'
        required: true
        default: i440fx
        type: choice
        options:
        - Q35
        - i440fx

jobs:
  build:
    runs-on: ubuntu-latest
    name: ç¼–è¯‘ "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          #  ä¸¤è¡Œä¸€ç»„ï¼Œåˆ é™¤ä¸éœ€è¦çš„ç‰ˆæœ¬
          #- platform: ds1621p
          #  version: 7.0.1-42218
          #- platform: ds1621p
          #  version: 7.1.0-42661

          #- platform: ds2422p
          #  version: 7.0.1-42218

          #- platform: ds3615xs
          #  version: 6.2.4-25556
          #- platform: ds3615xs
          #  version: 7.0.1-42218
          - platform: ds3615xs
            version: 7.1.0-42661

          #- platform: ds3617xs
          #  version: 7.0.1-42218
          #- platform: ds3617xs
          #  version: 7.1.0-42661

          #- platform: ds3622xsp
          #  version: 7.0.1-42218
          #- platform: ds3622xsp
          #  version: 7.1.0-42661

          #- platform: ds918p
          #  version: 6.2.4-25556
          #- platform: ds918p
          #  version: 7.0.1-42218
          - platform: ds918p
            version: 7.1.0-42661

          #- platform: ds920p
          #  version: 7.0.1-42218
          - platform: ds920p
            version: 7.1.0-42661

          #- platform: dva3221
          #  version: 7.0.1-42218
          #- platform: dva3221
          #  version: 7.1.0-42661

    steps:
      - name: æ£€å‡ºé¡¹ç›®æ–‡ä»¶
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/substring-action substract version for dtb folder
      - name: è·å¾—Subversion 
        uses: bhowell2/github-substring-action@v1
        id: subver
        with:
          value: ${{matrix.version}}
          index_of_str: "-"

      - name: ç¼“å­˜åŠ é€Ÿ
        uses: actions/cache@v3
        with:
          path: |
            cache/*.pat
            cache/*.org
            docker/downloads/*.txz
          key: ${{matrix.platform}}-${{matrix.version}}-${{ hashFiles('global_config.json') }}
          restore-keys: ${{matrix.platform}}-${{matrix.version}}-

      - name: æ¸…ç†ç¼“å­˜
        if: "${{ github.event.inputs.clean_cache == 'true' }}"
        run: |
          rm -rf cache/*.pat
          rm -rf cache/*.org
          rm -rf docker/downloads/*.txz
    
      # ç¬¬ä¸€ä¸ªç›˜ä¸ºè™šæ‹Ÿçš„SATAç›˜ã€‚
      - name: Variable
        id: var
        run: |
          case ${{ github.event.inputs.type_VM }} in
            Q35)
                _SataPM="6"
                _DiskIM="00"
                _dtbValue="00:1f.2"
                ;;
            i440fx)
                _SataPM="62"
                _DiskIM="0002"
                _dtbValue="00:04.0"
                ;;
            *)
                echo "Wrong type of VM"
                ;;
          esac
    
          echo ::set-output name=SataPM::$_SataPM
          echo ::set-output name=DiskIM::$_DiskIM
          echo ::set-output name=dtbValue::$_dtbValue
        
      - name: å‡†å¤‡æ„å»ºç¯å¢ƒ
        run: |
          ./redpill_tool_chain.sh build ${{matrix.platform}}-${{matrix.version}}

      - name: é…ç½®å¼•å¯¼é•œåƒ
        run: |
          cp sample_user_config.json ${{matrix.platform}}_user_config.json

          # è°ƒæ•´VIDå’ŒPID
          # sed -i -e 's/0x0001/0x88AA/g' -e 's/0x46f4/0x88AA/g' ${{matrix.platform}}_user_config.json

          # è°ƒæ•´SNå’ŒMAC,æœ€å¥½ä½¿ç”¨ actions secrets å¼•å…¥,SNåº”è¯¥æ˜¯å›ºå®šå€¼ä¸åº”è¯¥æ¯æ¬¡ç”Ÿæˆ
          sn=`./redpill_tool_chain.sh sn ${{matrix.platform}} | grep 'Serial Number' | awk '{print $3}'`
          sed -i -e "s/1234XXX123/${sn:="1130LWN123456"}/g" -e 's/XXYYXXYYXXYY/0011323D47F7/g' ${{matrix.platform}}_user_config.json

          # æ·»åŠ ç¬¬äºŒå¼ ç½‘å¡macå¹¶è®¾ç½®ç½‘å¡æ•°é‡
          sed -i -e 's/0011323D47F7"/&,\n\t"mac2": "0011323D47F8",\n\t"SasIdxMap": "0",\n\t"SataPortMap": "${{ steps.var.outputs.SataPM }}",\n\t"DiskIdxMap": "${{ steps.var.outputs.DiskIM }}",\n\t"netif_num": 2/g' ${{matrix.platform}}_user_config.json

          # è°ƒæ•´synoinfo
          sed -i -e 's/"synoinfo": {},/"synoinfo": {\n\t"maxlanport": "2"\n    },/g' ${{matrix.platform}}_user_config.json
          cat ${{matrix.platform}}_user_config.json

      - name: æ·»åŠ æ‰©å±•é©±åŠ¨
        if: matrix.platform != 'dva3221'
        run: |
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-boot-wait.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/redpill-load/master/redpill-acpid/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/redpill-load/master/redpill-virtio/rpext-index.json

      - name: æ·»åŠ æ‰©å±•é©±åŠ¨[r8125]
        if: matrix.platform != 'ds920p' && matrix.platform != 'ds918p'
        run: |
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8125/rpext-index.json
          
      - name: æ·»åŠ æ‰©å±•é©±åŠ¨[r8125 and r8152]
        if: matrix.platform == 'ds920p' || matrix.platform == 'ds918p'
        run: |
          ./redpill_tool_chain.sh add https://github.com/jinlife/redpill-tool-chain/raw/master/extensions/pocopico-r8125.json
          ./redpill_tool_chain.sh add https://github.com/jinlife/redpill-tool-chain/raw/master/extensions/pocopico-r8152.json
          
      - name: æ·»åŠ æ‰©å±•é©±åŠ¨[dva3221]
        if: matrix.platform == 'dva3221'
        run: |
          echo 'ç­‰å¾…æ•´ç†å…¼å®¹æ€§æ‰©å±•~ğŸ˜€'
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-boot-wait.json

      - name: æ·»åŠ  Misc shell
        run: |
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/redpill-load/master/redpill-misc/rpext-index.json

      - name: æ·»åŠ  jumkey.dtb !!!Create your own device tree binary!!!
        if: matrix.platform == 'ds920p' || matrix.platform == 'ds1621p' || matrix.platform == 'ds2422p'
        run: |
          ./redpill_tool_chain.sh add https://github.com/jinlife/redpill-tool-chain/raw/master/extensions/redpill-dtb.json
          #./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/redpill-load/develop/redpill-dtb/rpext-index.json
          echo '!!!Create your own device tree binary!!!'
          echo 'see https://github.com/jumkey/redpill-load/blob/develop/redpill-dtb/README.md'

      - name: é¢„å¤„ç†PAT
        if: endsWith(matrix.version, '42661') && startsWith(matrix.platform, 'ds361')
        run: |
          sed -i 's/debian:8-slim/debian:10-slim/g' global_config.json
          ./redpill_tool_chain.sh build ${{matrix.platform}}-${{matrix.version}}
          ./redpill_tool_chain.sh pat ${{matrix.platform}}-${{matrix.version}}
          sed -i 's/debian:10-slim/debian:8-slim/g' global_config.json
          ./redpill_tool_chain.sh build ${{matrix.platform}}-${{matrix.version}}

      - name: ç¼–è¯‘å¼•å¯¼é•œåƒ
        run: |
          ./redpill_tool_chain.sh auto ${{matrix.platform}}-${{matrix.version}}

      - name: Modify jumkey.dtb
        if: matrix.platform == 'ds920p' || matrix.platform == 'ds1621p' || matrix.platform == 'ds2422p'
        run: |
           echo 'redpill-dtb-dir'
           ls custom/extensions
           cd custom/extensions/redpill-dtb/${{matrix.platform}}_${{steps.subver.outputs.substring}}
           #cd custom/extensions/jumkey.dtb/${{matrix.platform}}_${{steps.subver.outputs.substring}}
           sudo chmod -R 777 ./
           sudo chmod +x dtc
           #ls          
           ./dtc -I dtb -O dts -o output.dts model_${{matrix.platform}}.dtb
           # Jumkey "00:1e.0,01.0,07.0" pocopico "00:13.0,00.0"
           sed -i -e 's/"00:1e.0,01.0,07.0"/"${{ steps.var.outputs.dtbValue }}"/g' output.dts
           cat output.dts
           rm -rf model_${{matrix.platform}}.dtb
           ./dtc -I dts -O dtb -o model_${{matrix.platform}}.dtb output.dts
          
      - name: Build jumkey.dtb
        if: matrix.platform == 'ds920p' || matrix.platform == 'ds1621p' || matrix.platform == 'ds2422p'
        run: |
           sudo rm -rfv images/redpill-*.img
           sudo rm -rfv custom/extensions/redpill-boot-wait
           sudo rm -rfv cache/*
           ./redpill_tool_chain.sh auto ${{matrix.platform}}-${{matrix.version}}

      - name: ä¸Šä¼ å¼•å¯¼é•œåƒåˆ° github actions
        uses: actions/upload-artifact@v3
        with:
          name: dsm-${{matrix.platform}}-${{matrix.version}}
          path: images/redpill-*.img
          if-no-files-found: error

      - name: åˆ é™¤æ—§çš„å·¥ä½œæµ
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
